spring:
  application:
    name: notifier
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    database-change-log-table: notifier_database_changelog
    database-change-log-lock-table: notifier_database_changelog_lock
  config:
    import: "optional:configserver:http://config:8087"
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
  data:
    web:
      pageable:
        default-page-size: 20000
        max-page-size: 20000
        one-indexed-parameters: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifier
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: com.aviatickets.notifier.dto

server:
  port: 8089

logging:
  level:
    com.aviatickets: debug
